version: "3"
services:
  backend_dev:
    container_name: ${APP_NAME}_backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./storage:/var/www/storage
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}

  mysql:
    image: mysql:5.7
    #volumes:
    #  - ./data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true

  nginx:
    container_name: ${APP_NAME}_nginx
    build:
      context: ./deploy/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=backend_dev
    links:
      - backend_dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:ro
      - ./deploy/nginx/sites-available/:/etc/nginx/sites-available/
    depends_on:
      - backend_dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment: 
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    links:
      - mysql
    depends_on:
      - mysql
